set echo on
set feedback 1
set pagesize 999
set trimspool on
set lINesize 200
set tab off
clear columns


/* Ho Yeung Chan */

/*  Task 00 */
SELECT user, sysdate 
FROM dual;

/*  Task 01 */
SELECT BOOKS.BOOK_ID
, BOOKS.TITLE
FROM BK_BOOKS BOOKS
WHERE BOOKS.BOOK_ID IN(
	SELECT BOOKTOPICS.BOOK_ID
	FROM BK_BOOK_TOPICS BOOKTOPICS
	WHERE BOOKTOPICS.TOPIC_ID = 'DB'
	OR BOOKTOPICS.TOPIC_ID = 'SQL'
	)
	AND BOOKS.BOOK_ID IN(
	SELECT ORDERS.BOOK_ID
	FROM BK_ORDER_DETAILS ORDERS
	)
	ORDER BY BOOKS.BOOK_ID		
;

/*  Task 02  */ 
SELECT BOOKS.BOOK_ID
, BOOKS.TITLE
FROM BK_BOOKS BOOKS
WHERE BOOKS.BOOK_ID IN
		(SELECT BOOKTOPICS.BOOK_ID
		FROM BK_BOOK_TOPICS BOOKTOPICS
		WHERE BOOKTOPICS.TOPIC_ID = 'DB')
		AND BOOKS.BOOK_ID IN
		(SELECT BOOKTOPICS.BOOK_ID
		FROM BK_BOOK_TOPICS BOOKTOPICS
		WHERE BOOKTOPICS.TOPIC_ID = 'SQL'
		)
 		AND BOOKS.BOOK_ID IN
		(SELECT ORDERS.BOOK_ID
		FROM BK_ORDER_DETAILS ORDERS
		)
ORDER BY BOOKS.BOOK_ID		
;

/*  Task 03 */
SELECT BOOKS.BOOK_ID
, BOOKS.TITLE
FROM BK_BOOKS BOOKS
WHERE BOOKS.BOOK_ID IN(
		SELECT BOOKTOPICS.BOOK_ID
		FROM BK_BOOK_TOPICS BOOKTOPICS
		WHERE BOOKTOPICS.TOPIC_ID = 'SQL'
		)
		AND BOOKS.BOOK_ID NOT IN(
		SELECT BOOKTOPICS.BOOK_ID
		FROM BK_BOOK_TOPICS BOOKTOPICS
		WHERE BOOKTOPICS.TOPIC_ID = 'DB'
		)
		AND BOOKS.BOOK_ID IN(
		SELECT ORDERS.BOOK_ID
		FROM BK_ORDER_DETAILS ORDERS
		)
ORDER BY BOOKS.BOOK_ID		
;


/*  Task 04 */ 
SELECT CUS.CUST_ID
, CUS.CUST_NAME_LAST
FROM BK_CUSTOMERS CUS
WHERE CUS.CUST_ID IN(
        SELECT HEADER.CUST_ID
        FROM BK_ORDER_HEADERS HEADER
        WHERE HEADER.ORDER_ID IN(
            SELECT ORDERS.ORDER_ID
            FROM BK_ORDER_DETAILS ORDERS
            WHERE ORDERS.BOOK_ID IN(
                SELECT BOOKTOPICS.BOOK_ID
                FROM BK_BOOK_TOPICS BOOKTOPICS
                WHERE BOOKTOPICS.TOPIC_ID = 'HIST')))
        AND EXTRACT(YAER FROM ORDER_DATE) = EXTRACT(YEAR FROM SYSDATE)
ORDER BY CUS.CUST_ID
;

/* Task 05 */
with BOOK_COPYSOLD AS(
	SELECT ORDERS.BOOK_ID AS BOOK_ID
	, SUM(NVL(ORDERS.QUANTITY, 0)) AS COPY_SOLD
	FROM BK_ORDER_DETAILS ORDERS
	GROUP BY ORDERS.BOOK_ID
	)
SELECT BOOKS.BOOK_ID
, BOOKS.TITLE
FROM BK_BOOKS BOOKS
WHERE BOOKS.BOOK_ID IN(
	SELECT SOLD.BOOK_ID
	FROM BOOK_COPYSOLD SOLD
	WHERE SOLD.COPY_SOLD > 500
	)
ORDER BY BOOKS.BOOK_ID
;

/*  Task 06 */
with ORDER_STATISTICS AS(
	SELECT OYM.YEAR_MONTH
	, COUNT(OYM.ORDER_ID) AS NUM_OF_ORDERS
	FROM(
		SELECT HEADER.ORDER_ID
		, TO_CHAR(HEADER.ORDER_DATE, 'YYYY') || '.' || TO_CHAR(HEADER.ORDER_DATE, 'MM') AS YEAR_MONTH
		FROM BK_ORDER_HEADERS HEADER) 
		OYM
	GROUP BY OYM.YEAR_MONTH)
SELECT ORDERS.YEAR_MONTH
FROM ORDER_STATISTICS ORDERS
WHERE ORDERS.NUM_OF_ORDERS = (
	SELECT MIN(NUM_OF_ORDERS)
	FROM ORDER_STATISTICS)
ORDER BY ORDERS.YEAR_MONTH DESC
;

/*  Task 07 */
with ORDER_STATISTICS AS(
	SELECT OYM.YEAR_MONTH
	, COUNT(OYM.ORDER_ID) AS NUM_OF_ORDERS
	FROM(
		SELECT HEADER.ORDER_ID
		, TO_CHAR(HEADER.ORDER_DATE, 'YYYY') || '.' || TO_CHAR(HEADER.ORDER_DATE, 'MM') AS YEAR_MONTH
		FROM BK_ORDER_HEADERS HEADER) 
		OYM
		GROUP BY OYM.YEAR_MONTH)
SELECT ORDERS.YEAR_MONTH
FROM ORDER_STATISTICS ORDERS
WHERE ORDERS.NUM_OF_ORDERS = (
		SELECT MAX(NUM_OF_ORDERS)
		FROM ORDER_STATISTICS 
		)
ORDER BY ORDERS.YEAR_MONTH DESC
;

