set echo on
set feedback 1
set pagesize 999
set trimspool on
set linesize 200
set tab off
clear columns


/* Ho Yeung Chan */

/*  TASK  */
select user, sysdate 
FROM dual;

/*  TASK 1 */
CREATE OR REPLACE VIEW bkOrdersPriorYear
AS (
	SELECT DISTINCT 
	cust_id AS CUSTOMERID
	, TO_CHAR(order_date, 'MON') AS ORDERMONTH
	, CASE 
		WHEN (cust_name_first IS NULL AND cust_name_last IS NOT NULL) THEN cust_name_last 
		WHEN (cust_name_first IS NOT NULL AND cust_name_last IS NULL) THEN cust_name_first
		ELSE cust_name_last ||', '|| cust_name_first 
	END AS CUSTOMERNAME
	FROM bk_order_headers
	JOIN bk_customers USING (cust_id)
	WHERE EXTRACT(year FROM order_date) = EXTRACT(year FROM SYSDATE)-1
);

/*  TASK 2  */ 
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH = 'MAR'
INTERSECT
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH = 'JUN'
INTERSECT
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH = 'SEP'
;

/*  TASK 3 */
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH= 'APR'
UNION
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH= 'JUN'
UNION
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH= 'AUG'
;


/*  TASK 4 */ 
(SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH= 'APR'
INTERSECT
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH= 'MAY')
MINUS
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH= 'JUN'
;

/*  TASK 5 */
(SELECT CUSTOMERID
, CUSTOMERNAME	
FROM bkOrdersPriorYear
WHERE ORDERMONTH= 'MAR'
UNION
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH= 'JUN')
MINUS
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH= 'SEP'
;

/*  TASK 6 */
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
MINUS
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH = 'MAR'
MINUS
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH = 'JUN'
MINUS
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH = 'SEP'
;



/*  TASK 7 */
SELECT CUSTOMERID
, CUSTOMERNAME	
FROM bkOrdersPriorYear
WHERE ORDERMONTH= 'JAN'
MINUS
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH = 'FEB'
MINUS
SELECT CUSTOMERID
, CUSTOMERNAME
FROM bkOrdersPriorYear
WHERE ORDERMONTH = 'MAR'
;


